#volumes:
#  pg_keycloak:
#
#services:
#  keycloak_db:
#    image: postgres
#    container_name: keycloak_db
#    restart: unless-stopped
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=1234
#      - POSTGRES_DB=keycloak
#    volumes:
#      - pg_keycloak:/var/lib/postgresql/data
#    ports:
#      - "5433:5432"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres"]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#    networks:
#      - keycloak_net
#
#  keycloak:
#    build: .
#    container_name: keycloak
##    environment:
##      KC_DB: postgres
##      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
##      KC_DB_USERNAME: postgres
##      KC_DB_PASSWORD: 1234
##      KC_BOOTSTRAP_ADMIN_USERNAME: admin
##      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
##      KC_HOSTNAME: localhost
##      KC_HTTP_PORT: 8080
##      KC_SCRIPT_DEFAULT_ENABLED: "true"
#    depends_on:
#      keycloak_db:
#        condition: service_healthy
#    healthcheck:
#      test: [ "CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/8080'" ]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#    ports:
#      - "8080:8080"
#    networks:
#      - keycloak_net
#
#networks:
#  keycloak_net: